<a href="https://colab.research.google.com/github/Reave-ng/myportfolio/blob/main/FIN559_Linear_Regression_Non_gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import mean_squared_error, r2_score


# Linear Regression Example



The coefficients, the residual sum of squares and the variance score are also
calculated.




In [ ]:
#load the CSV file as dataframe
data = pd.read_csv("calories.csv", index_col=False)

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
data.shape

(506, 14)

In [ ]:
print (data.columns) #prints the column names of the dataframe "data"

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [ ]:
X = data.drop(['medv'], axis=1) #selects the first 13 columns in data dataframe

In [ ]:
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [ ]:
X.shape

(506, 13)

In [ ]:
#Y = data.medv
Y = data['medv']
Y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

In [ ]:
type(Y)

pandas.core.series.Series

In [ ]:
Y.shape

(506,)

In [ ]:
X.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [ ]:
X.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
dtype: int64

In [ ]:
X.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
dtype: int64

In [ ]:
#split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2) #80% for train and 20% for testing

In [ ]:
X_train.shape

(404, 13)

In [ ]:
Y_train.shape

(404,)

In [ ]:
506*0.8

404.8

In [ ]:
X_test.shape

(102, 13)

In [ ]:
Y_test.shape

(102,)

In [ ]:
xa = X_train
xa.head(2)

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
333  0.05083  0.0   5.19     0  0.515  6.316  38.1  6.4584    5  224     20.2   
342  0.02498  0.0   1.89     0  0.518  6.540  59.7  6.2669    1  422     15.9   

          b  lstat  
333  389.71   5.68  
342  389.96   8.65

In [ ]:
xa['medv'] = Y_train #create a new column MEDV in 'xa' dataframe and store Y_train values in it
xa.head(2)

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
333  0.05083  0.0   5.19     0  0.515  6.316  38.1  6.4584    5  224     20.2   
342  0.02498  0.0   1.89     0  0.518  6.540  59.7  6.2669    1  422     15.9   

          b  lstat  medv  
333  389.71   5.68  22.2  
342  389.96   8.65  16.5

In [ ]:
corr = xa.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
print (corr)

             crim        zn     indus      chas       nox        rm       age  \
crim     1.000000 -0.207599  0.414292 -0.054686  0.436255 -0.203906  0.358552   
zn      -0.207599  1.000000 -0.540272 -0.033218 -0.529789  0.340536 -0.579034   
indus    0.414292 -0.540272  1.000000  0.068670  0.757979 -0.400648  0.642090   
chas    -0.054686 -0.033218  0.068670  1.000000  0.111236  0.070540  0.092483   
nox      0.436255 -0.529789  0.757979  0.111236  1.000000 -0.309523  0.737937   
rm      -0.203906  0.340536 -0.400648  0.070540 -0.309523  1.000000 -0.259724   
age      0.358552 -0.579034  0.642090  0.092483  0.737937 -0.259724  1.000000   
dis     -0.385070  0.662830 -0.705044 -0.112240 -0.778801  0.202133 -0.748456   
rad      0.625706 -0.329976  0.617133 -0.006098  0.650418 -0.227899  0.471959   
tax      0.579056 -0.328838  0.740278 -0.030089  0.689526 -0.304967  0.514446   
ptratio  0.299994 -0.416463  0.425486 -0.134624  0.251243 -0.409635  0.275725   
b       -0.410862  0.173349 

In [ ]:
X_new = X_train[['rm','ptratio','lstat']]
X_new_test = X_test[['rm','ptratio','lstat']]
X_new.head()

rm  ptratio  lstat
333  6.316     20.2   5.68
342  6.540     15.9   8.65
338  6.059     20.2   8.51
218  5.951     16.4  17.92
258  7.333     13.0   7.79

In [ ]:
X_new.shape

(404, 3)

In [ ]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_new, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_new_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(Y_test, Y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(Y_test, Y_pred))


Coefficients: 
 [ 5.18484576 -0.89009084 -0.56196742]
Mean squared error: 46.47
Variance score: 0.52


In [ ]:
print (regr.coef_)
#['rm','ptratio','lstat']#

[ 5.18484576 -0.89009084 -0.56196742]


In [ ]:
regr.intercept_

13.327620017049096

MEDV = theta_0 + theta_1*x_1+ theta_2*x_2 ....+ theta_13*x_13

In [ ]:
# we are now going to scale the date and see the performance
from sklearn.preprocessing import StandardScaler #x-mean/standard_dev
scaler = StandardScaler()
X_new1 = scaler.fit_transform(X_new) #X_new1 is my scaled data
X_new_test1 = scaler.transform(X_new_test) #the scaler is already trained with u and s values

In [ ]:
type(X_new1)

numpy.ndarray

In [ ]:
X_new1

array([[ 0.0393977 ,  0.80225551, -0.99277641],
       [ 0.37148918, -1.19070641, -0.56426573],
       [-0.34161797,  0.80225551, -0.58446488],
       ...,
       [-0.6084772 ,  0.29242804,  0.72415191],
       [-0.23635683, -1.74688183,  2.19869034],
       [ 1.00602111,  0.80225551,  0.67076842]])

In [ ]:
X_new.head()

rm  ptratio  lstat
333  6.316     20.2   5.68
342  6.540     15.9   8.65
338  6.059     20.2   8.51
218  5.951     16.4  17.92
258  7.333     13.0   7.79

In [ ]:
Y_train = pd.DataFrame(Y_train, columns=['medv'])

Y_test = pd.DataFrame(Y_test, columns=['medv'])

In [ ]:
Y_train.head()

medv
333  22.2
342  16.5
338  20.6
218  21.5
258  36.0

In [ ]:
scaler_y = StandardScaler()
Y_train1 = scaler_y.fit_transform(Y_train)
Y_test1 = scaler_y.transform(Y_test)

In [ ]:
# Create linear regression object
regr1 = linear_model.LinearRegression()

# Train the model using the training sets
regr1.fit(X_new1, Y_train1)

# Make predictions using the testing set
Y_pred1 = regr1.predict(X_new_test1)

# The coefficients
print('Coefficients: \n', regr1.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(Y_test1, Y_pred1))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(Y_test1, Y_pred1))

Coefficients: 
 [[ 0.38808149 -0.21310841 -0.43221789]]
Mean squared error: 0.57
Variance score: 0.52


In [ ]:
regr1.intercept_

array([-4.680892e-17])